version: "3.6"

services:
  mysql:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: weather
      MYSQL_PASSWORD: wheather
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redis:/data
    depends_on:
      - mysql
